# Generated by Django 5.1.4 on 2025-01-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('S', 'sale'), ('R', 'rent')], max_length=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.PositiveIntegerField()),
                ('bed_count', models.PositiveIntegerField()),
                ('bath_count', models.PositiveIntegerField()),
                ('garage_count', models.PositiveIntegerField()),
            ],
        ),
    ]
