# Generated by Django 5.1.4 on 2025-01-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_reserve_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('R', 'rent'), ('S', 'sale')], max_length=10),
        ),
    ]
