# Generated by Django 5.1.4 on 2025-01-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('S', 'sale'), ('R', 'rent')], max_length=10),
        ),
    ]
