# Generated by Django 5.1.4 on 2025-01-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
